//// Generated by starflame_db_kit from snapshot 0005_check (c6c567f28ebf5bea). Do not edit;
//// run `gleam run -m db_kit -- codegen` to regenerate.

import gleam/dynamic/decode
import gleam/int
import gleam/javascript/promise
import gleam/list
import gleam/option
import gleam/string
import gleam/time/timestamp
import starflame/d1
import starflame_db/runtime

pub type Comment {
  Comment(id: Int, post_id: Int, editor_id: option.Option(Int), body: String)
}

pub type NewComment {
  NewComment(post_id: Int, editor_id: option.Option(Int), body: String)
}

pub const comment_columns = "\"id\", \"post_id\", \"editor_id\", \"body\""

pub fn comment_decoder() -> decode.Decoder(Comment) {
  use id <- decode.field("id", d1.int_decoder())
  use post_id <- decode.field("post_id", d1.int_decoder())
  use editor_id <- decode.field("editor_id", decode.optional(d1.int_decoder()))
  use body <- decode.field("body", decode.string)
  decode.success(Comment(id:, post_id:, editor_id:, body:))
}

pub fn insert_comment(
  db: d1.Database,
  new: NewComment,
) -> promise.Promise(Result(Comment, d1.Error)) {
  let values =
    [
      option.Some(#("\"post_id\"", d1.int(new.post_id))),
      option.Some(#("\"editor_id\"", d1.nullable(new.editor_id, d1.int))),
      option.Some(#("\"body\"", d1.string(new.body))),
    ]
    |> list.filter_map(fn(value) {
      case value {
        option.Some(value) -> Ok(value)
        option.None -> Error(Nil)
      }
    })
  let sql = case values {
    [] ->
      "INSERT INTO \"comments\" DEFAULT VALUES RETURNING " <> comment_columns
    _ ->
      "INSERT INTO \"comments\" ("
      <> string.join(list.map(values, fn(value) { value.0 }), ", ")
      <> ") VALUES ("
      <> string.join(list.map(values, fn(_) { "?" }), ", ")
      <> ") RETURNING "
      <> comment_columns
  }
  d1.all(db, sql, list.map(values, fn(value) { value.1 }), comment_decoder())
  |> promise.map(fn(result) {
    case result {
      Ok([row]) -> Ok(row)
      Ok(rows) ->
        Error(
          d1.DecodeError([
            decode.DecodeError(
              "one row",
              int.to_string(list.length(rows)) <> " rows",
              [],
            ),
          ]),
        )
      Error(error) -> Error(error)
    }
  })
}

pub fn get_comment(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(option.Option(Comment), d1.Error)) {
  d1.all(
    db,
    "SELECT \"id\", \"post_id\", \"editor_id\", \"body\" FROM \"comments\" WHERE \"id\" = ?",
    [d1.int(id)],
    comment_decoder(),
  )
  |> promise.map(fn(result) {
    case result {
      Ok([row, ..]) -> Ok(option.Some(row))
      Ok([]) -> Ok(option.None)
      Error(error) -> Error(error)
    }
  })
}

pub fn delete_comment(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(Bool, d1.Error)) {
  d1.run(db, "DELETE FROM \"comments\" WHERE \"id\" = ?", [d1.int(id)])
  |> promise.map(fn(result) {
    case result {
      Ok(changes) -> Ok(changes > 0)
      Error(error) -> Error(error)
    }
  })
}

pub type Post {
  Post(
    id: Int,
    user_id: Int,
    title: String,
    slug: String,
    body: option.Option(String),
    type_: String,
    rating: option.Option(Float),
  )
}

pub type NewPost {
  NewPost(
    user_id: Int,
    title: String,
    slug: runtime.Defaulted(String),
    body: runtime.Defaulted(option.Option(String)),
    type_: runtime.Defaulted(String),
    rating: option.Option(Float),
  )
}

pub const post_columns = "\"id\", \"user_id\", \"title\", \"slug\", \"body\", \"type\", \"rating\""

pub fn post_decoder() -> decode.Decoder(Post) {
  use id <- decode.field("id", d1.int_decoder())
  use user_id <- decode.field("user_id", d1.int_decoder())
  use title <- decode.field("title", decode.string)
  use slug <- decode.field("slug", decode.string)
  use body <- decode.field("body", decode.optional(decode.string))
  use type_ <- decode.field("type", decode.string)
  use rating <- decode.field("rating", decode.optional(decode.float))
  decode.success(Post(id:, user_id:, title:, slug:, body:, type_:, rating:))
}

pub fn insert_post(
  db: d1.Database,
  new: NewPost,
) -> promise.Promise(Result(Post, d1.Error)) {
  let values =
    [
      option.Some(#("\"user_id\"", d1.int(new.user_id))),
      option.Some(#("\"title\"", d1.string(new.title))),
      case new.slug {
        runtime.UseDefault -> option.None
        runtime.Given(value) -> option.Some(#("\"slug\"", d1.string(value)))
      },
      case new.body {
        runtime.UseDefault -> option.None
        runtime.Given(value) ->
          option.Some(#("\"body\"", d1.nullable(value, d1.string)))
      },
      case new.type_ {
        runtime.UseDefault -> option.None
        runtime.Given(value) -> option.Some(#("\"type\"", d1.string(value)))
      },
      option.Some(#("\"rating\"", d1.nullable(new.rating, d1.float))),
    ]
    |> list.filter_map(fn(value) {
      case value {
        option.Some(value) -> Ok(value)
        option.None -> Error(Nil)
      }
    })
  let sql = case values {
    [] -> "INSERT INTO \"posts\" DEFAULT VALUES RETURNING " <> post_columns
    _ ->
      "INSERT INTO \"posts\" ("
      <> string.join(list.map(values, fn(value) { value.0 }), ", ")
      <> ") VALUES ("
      <> string.join(list.map(values, fn(_) { "?" }), ", ")
      <> ") RETURNING "
      <> post_columns
  }
  d1.all(db, sql, list.map(values, fn(value) { value.1 }), post_decoder())
  |> promise.map(fn(result) {
    case result {
      Ok([row]) -> Ok(row)
      Ok(rows) ->
        Error(
          d1.DecodeError([
            decode.DecodeError(
              "one row",
              int.to_string(list.length(rows)) <> " rows",
              [],
            ),
          ]),
        )
      Error(error) -> Error(error)
    }
  })
}

pub fn get_post(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(option.Option(Post), d1.Error)) {
  d1.all(
    db,
    "SELECT \"id\", \"user_id\", \"title\", \"slug\", \"body\", \"type\", \"rating\" FROM \"posts\" WHERE \"id\" = ?",
    [d1.int(id)],
    post_decoder(),
  )
  |> promise.map(fn(result) {
    case result {
      Ok([row, ..]) -> Ok(option.Some(row))
      Ok([]) -> Ok(option.None)
      Error(error) -> Error(error)
    }
  })
}

pub fn delete_post(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(Bool, d1.Error)) {
  d1.run(db, "DELETE FROM \"posts\" WHERE \"id\" = ?", [d1.int(id)])
  |> promise.map(fn(result) {
    case result {
      Ok(changes) -> Ok(changes > 0)
      Error(error) -> Error(error)
    }
  })
}

pub type User {
  User(
    id: Int,
    email: String,
    display_name: String,
    admin: Bool,
    created_at: timestamp.Timestamp,
    bio: option.Option(String),
  )
}

pub type NewUser {
  NewUser(
    email: String,
    display_name: String,
    admin: runtime.Defaulted(Bool),
    created_at: runtime.Defaulted(timestamp.Timestamp),
    bio: option.Option(String),
  )
}

pub const user_columns = "\"id\", \"email\", \"display_name\", \"admin\", \"created_at\", \"bio\""

pub fn user_decoder() -> decode.Decoder(User) {
  use id <- decode.field("id", d1.int_decoder())
  use email <- decode.field("email", decode.string)
  use display_name <- decode.field("display_name", decode.string)
  use admin <- decode.field("admin", d1.bool_decoder())
  use created_at <- decode.field("created_at", runtime.timestamp_decoder())
  use bio <- decode.field("bio", decode.optional(decode.string))
  decode.success(User(id:, email:, display_name:, admin:, created_at:, bio:))
}

pub fn insert_user(
  db: d1.Database,
  new: NewUser,
) -> promise.Promise(Result(User, d1.Error)) {
  let values =
    [
      option.Some(#("\"email\"", d1.string(new.email))),
      option.Some(#("\"display_name\"", d1.string(new.display_name))),
      case new.admin {
        runtime.UseDefault -> option.None
        runtime.Given(value) -> option.Some(#("\"admin\"", d1.bool(value)))
      },
      case new.created_at {
        runtime.UseDefault -> option.None
        runtime.Given(value) ->
          option.Some(#("\"created_at\"", runtime.timestamp_value(value)))
      },
      option.Some(#("\"bio\"", d1.nullable(new.bio, d1.string))),
    ]
    |> list.filter_map(fn(value) {
      case value {
        option.Some(value) -> Ok(value)
        option.None -> Error(Nil)
      }
    })
  let sql = case values {
    [] -> "INSERT INTO \"users\" DEFAULT VALUES RETURNING " <> user_columns
    _ ->
      "INSERT INTO \"users\" ("
      <> string.join(list.map(values, fn(value) { value.0 }), ", ")
      <> ") VALUES ("
      <> string.join(list.map(values, fn(_) { "?" }), ", ")
      <> ") RETURNING "
      <> user_columns
  }
  d1.all(db, sql, list.map(values, fn(value) { value.1 }), user_decoder())
  |> promise.map(fn(result) {
    case result {
      Ok([row]) -> Ok(row)
      Ok(rows) ->
        Error(
          d1.DecodeError([
            decode.DecodeError(
              "one row",
              int.to_string(list.length(rows)) <> " rows",
              [],
            ),
          ]),
        )
      Error(error) -> Error(error)
    }
  })
}

pub fn get_user(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(option.Option(User), d1.Error)) {
  d1.all(
    db,
    "SELECT \"id\", \"email\", \"display_name\", \"admin\", \"created_at\", \"bio\" FROM \"users\" WHERE \"id\" = ?",
    [d1.int(id)],
    user_decoder(),
  )
  |> promise.map(fn(result) {
    case result {
      Ok([row, ..]) -> Ok(option.Some(row))
      Ok([]) -> Ok(option.None)
      Error(error) -> Error(error)
    }
  })
}

pub fn delete_user(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(Bool, d1.Error)) {
  d1.run(db, "DELETE FROM \"users\" WHERE \"id\" = ?", [d1.int(id)])
  |> promise.map(fn(result) {
    case result {
      Ok(changes) -> Ok(changes > 0)
      Error(error) -> Error(error)
    }
  })
}
