-- Generated by starflame_db_kit. Review before applying with `wrangler d1 migrations apply`.
-- parent: none
-- snapshot: 6feae39309e71347

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "google_subject" TEXT UNIQUE,
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch())
) STRICT;
CREATE TABLE "notes" (
  "id" INTEGER PRIMARY KEY,
  "user_id" INTEGER NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "body" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch())
) STRICT;
CREATE INDEX "notes_user_idx" ON "notes" ("user_id");
