//// Generates the typed D1 interface from a frozen schema snapshot.

import gleam/list
import gleam/option.{None, Some}
import gleam/string
import starflame_db/schema.{type Column, type Kind, type Table}
import starflame_db_kit/snapshot.{type Snapshot}

pub fn module(snapshot: Snapshot) -> String {
  let tables = snapshot.canonical(snapshot.schema).tables
  let imports =
    case tables {
      [] -> []
      _ -> [
        "import gleam/dynamic/decode",
        "import gleam/javascript/promise",
        "import gleam/list",
        "import gleam/option",
        "import gleam/string",
        "import starflame/d1",
      ]
    }
    |> list.append(case list.any(tables, table_uses_timestamp) {
      True -> ["import gleam/time/timestamp"]
      False -> []
    })
    |> list.append(case list.any(tables, table_uses_runtime) {
      True -> ["import starflame_db/runtime"]
      False -> []
    })
    |> list.append(case tables {
      [] -> []
      _ -> ["import gleam/int"]
    })
    |> list.sort(string.compare)
  let header =
    "//// Generated by starflame_db_kit from snapshot "
    <> snapshot.id
    <> " ("
    <> snapshot.hash(snapshot)
    <> "). Do not edit;\n//// run `gleam run -m db_kit -- codegen` to regenerate."
  string.join(
    [header, string.join(imports, "\n"), ..list.map(tables, table_module)],
    "\n\n",
  )
  <> "\n"
}

fn table_module(table: Table) -> String {
  string.join(
    [
      row_type(table),
      new_type(table),
      columns_constant(table),
      decoder(table),
      insert_function(table),
      get_function(table),
      delete_function(table),
    ],
    "\n\n",
  )
}

fn row_type(table: Table) -> String {
  let fields =
    list.map(table.columns, fn(column) {
      field_name(column.name) <> ": " <> column_type(column)
    })
  let constructor = table.row <> "(" <> string.join(fields, ", ") <> ")"
  let compact = "pub type " <> table.row <> " { " <> constructor <> " }"
  case string.length(compact) <= 80 {
    True -> compact
    False ->
      case string.length("  " <> constructor) <= 80 {
        True -> "pub type " <> table.row <> " {\n  " <> constructor <> "\n}"
        False ->
          "pub type "
          <> table.row
          <> " {\n  "
          <> table.row
          <> "(\n"
          <> string.join(
            list.map(fields, fn(field) { "    " <> field <> "," }),
            "\n",
          )
          <> "\n  )\n}"
      }
  }
}

fn new_type(table: Table) -> String {
  let columns = list.filter(table.columns, insertable)
  let head = "New" <> table.row
  case columns {
    [] -> "pub type New" <> table.row <> " { " <> head <> " }"
    _ -> {
      let fields =
        list.map(columns, fn(column) {
          field_name(column.name) <> ": " <> insert_type(column)
        })
      let constructor = head <> "(" <> string.join(fields, ", ") <> ")"
      let compact = "pub type New" <> table.row <> " { " <> constructor <> " }"
      case string.length(compact) <= 80 {
        True -> compact
        False ->
          case string.length("  " <> constructor) <= 80 {
            True ->
              "pub type New" <> table.row <> " {\n  " <> constructor <> "\n}"
            False ->
              "pub type New"
              <> table.row
              <> " {\n  "
              <> head
              <> "(\n"
              <> string.join(
                list.map(fields, fn(field) { "    " <> field <> "," }),
                "\n",
              )
              <> "\n  )\n}"
          }
      }
    }
  }
}

fn columns_constant(table: Table) -> String {
  "pub const "
  <> snake_case(table.row)
  <> "_columns = "
  <> gleam_string(
    table.columns
    |> list.map(fn(column) { quote_identifier(column.name) })
    |> string.join(", "),
  )
}

fn decoder(table: Table) -> String {
  let name = snake_case(table.row)
  let fields =
    list.map(table.columns, fn(column) {
      "  use "
      <> field_name(column.name)
      <> " <- decode.field("
      <> gleam_string(column.name)
      <> ", "
      <> column_decoder(column)
      <> ")"
    })
  "pub fn "
  <> name
  <> "_decoder() -> decode.Decoder("
  <> table.row
  <> ") {\n"
  <> string.join(fields, "\n")
  <> "\n  decode.success("
  <> table.row
  <> "("
  <> string.join(
    list.map(table.columns, fn(column) { field_name(column.name) <> ":" }),
    ", ",
  )
  <> "))\n}"
}

fn insert_function(table: Table) -> String {
  let row = table.row
  let name = snake_case(row)
  let columns = list.filter(table.columns, insertable)
  let values =
    list.map(columns, fn(column) { "      " <> insert_value(column) })
  let return_type = "promise.Promise(Result(" <> row <> ", d1.Error))"
  let compact_signature =
    "pub fn insert_"
    <> name
    <> "(db: d1.Database, new: New"
    <> row
    <> ") -> "
    <> return_type
    <> " {"
  let signature = case string.length(compact_signature) <= 80 {
    True -> compact_signature <> "\n"
    False ->
      "pub fn insert_"
      <> name
      <> "(\n  db: d1.Database,\n  new: New"
      <> row
      <> ",\n) -> "
      <> return_type
      <> " {\n"
  }
  let values_block = case columns {
    [] -> "  let values = []\n"
    _ ->
      "  let values =\n    [\n"
      <> string.join(values, ",\n")
      <> ",\n    ]\n"
      <> "    |> list.filter_map(fn(value) {\n"
      <> "      case value {\n"
      <> "        option.Some(value) -> Ok(value)\n"
      <> "        option.None -> Error(Nil)\n"
      <> "      }\n"
      <> "    })\n"
  }
  let default_value =
    gleam_string(
      "INSERT INTO "
      <> quote_identifier(table.name)
      <> " DEFAULT VALUES RETURNING ",
    )
    <> " <> "
    <> name
    <> "_columns"
  let default_branch = format_case_branch("[]", default_value)
  let sql =
    "  let sql = case values {\n"
    <> default_branch
    <> "\n    _ ->\n      "
    <> gleam_string("INSERT INTO " <> quote_identifier(table.name) <> " (")
    <> "\n      <> string.join(list.map(values, fn(value) { value.0 }), \", \")"
    <> "\n      <> \") VALUES (\""
    <> "\n      <> string.join(list.map(values, fn(_) { \"?\" }), \", \")"
    <> "\n      <> \") RETURNING \""
    <> "\n      <> "
    <> name
    <> "_columns\n  }\n"
  let all =
    "  d1.all(db, sql, list.map(values, fn(value) { value.1 }), "
    <> name
    <> "_decoder())"
  let all_call = case string.length(all) <= 80 {
    True -> all <> "\n"
    False ->
      "  d1.all(\n    db,\n    sql,\n    list.map(values, fn(value) { value.1 }),\n    "
      <> name
      <> "_decoder(),\n  )\n"
  }
  signature
  <> values_block
  <> sql
  <> all_call
  <> "  |> promise.map(fn(result) {\n"
  <> "    case result {\n"
  <> "      Ok([row]) -> Ok(row)\n"
  <> "      Ok(rows) ->\n"
  <> "        Error(\n"
  <> "          d1.DecodeError([\n"
  <> "            decode.DecodeError(\n"
  <> "              \"one row\",\n"
  <> "              int.to_string(list.length(rows)) <> \" rows\",\n"
  <> "              [],\n"
  <> "            ),\n"
  <> "          ]),\n"
  <> "        )\n"
  <> "      Error(error) -> Error(error)\n"
  <> "    }\n"
  <> "  })\n}"
}

fn format_case_branch(pattern: String, expression: String) -> String {
  let compact = "    " <> pattern <> " -> " <> expression
  case string.length(compact) <= 80 {
    True -> compact
    False -> "    " <> pattern <> " ->\n      " <> expression
  }
}

fn get_function(table: Table) -> String {
  let name = snake_case(table.row)
  let key = primary_key(table)
  let key_name = field_name(key.name)
  let key_type = base_type(key.kind)
  let return_type =
    "promise.Promise(Result(option.Option(" <> table.row <> "), d1.Error))"
  let columns =
    table.columns
    |> list.map(fn(column) { quote_identifier(column.name) })
    |> string.join(", ")
  let compact_signature =
    "pub fn get_"
    <> name
    <> "(db: d1.Database, "
    <> key_name
    <> ": "
    <> key_type
    <> ") -> "
    <> return_type
    <> " {"
  let signature = case string.length(compact_signature) <= 80 {
    True -> compact_signature <> "\n"
    False ->
      "pub fn get_"
      <> name
      <> "(\n  db: d1.Database,\n  "
      <> key_name
      <> ": "
      <> key_type
      <> ",\n) -> "
      <> return_type
      <> " {\n"
  }
  signature
  <> "  d1.all(\n"
  <> "    db,\n"
  <> "    "
  <> gleam_string(
    "SELECT "
    <> columns
    <> " FROM "
    <> quote_identifier(table.name)
    <> " WHERE "
    <> quote_identifier(key.name)
    <> " = ?",
  )
  <> ",\n"
  <> "    ["
  <> encode(key.kind, key_name)
  <> "],\n"
  <> "    "
  <> name
  <> "_decoder(),\n"
  <> "  )\n"
  <> "  |> promise.map(fn(result) {\n"
  <> "    case result {\n"
  <> "      Ok([row, ..]) -> Ok(option.Some(row))\n"
  <> "      Ok([]) -> Ok(option.None)\n"
  <> "      Error(error) -> Error(error)\n"
  <> "    }\n"
  <> "  })\n}"
}

fn delete_function(table: Table) -> String {
  let name = snake_case(table.row)
  let key = primary_key(table)
  let key_name = field_name(key.name)
  let key_type = base_type(key.kind)
  let return_type = "promise.Promise(Result(Bool, d1.Error))"
  let compact_signature =
    "pub fn delete_"
    <> name
    <> "(db: d1.Database, "
    <> key_name
    <> ": "
    <> key_type
    <> ") -> "
    <> return_type
    <> " {"
  let signature = case string.length(compact_signature) <= 80 {
    True -> compact_signature <> "\n"
    False ->
      "pub fn delete_"
      <> name
      <> "(\n  db: d1.Database,\n  "
      <> key_name
      <> ": "
      <> key_type
      <> ",\n) -> "
      <> return_type
      <> " {\n"
  }
  let query =
    "DELETE FROM "
    <> quote_identifier(table.name)
    <> " WHERE "
    <> quote_identifier(key.name)
    <> " = ?"
  let call =
    "  d1.run(db, "
    <> gleam_string(query)
    <> ", ["
    <> encode(key.kind, key_name)
    <> "])"
  signature
  <> case string.length(call) <= 80 {
    True -> call <> "\n"
    False ->
      "  d1.run(\n    db,\n    "
      <> gleam_string(query)
      <> ",\n    ["
      <> encode(key.kind, key_name)
      <> "],\n  )\n"
  }
  <> "  |> promise.map(fn(result) {\n"
  <> "    case result {\n"
  <> "      Ok(changes) -> Ok(changes > 0)\n"
  <> "      Error(error) -> Error(error)\n"
  <> "    }\n"
  <> "  })\n}"
}

fn insert_value(column: Column) -> String {
  let field = field_name(column.name)
  let column_sql = gleam_string(quote_identifier(column.name))
  case column.default {
    Some(_) -> {
      let given =
        "option.Some(#("
        <> column_sql
        <> ", "
        <> insert_encoding(column, "value")
        <> "))"
      "case new."
      <> field
      <> " {\n        runtime.UseDefault -> option.None\n"
      <> format_case_arm("        ", "runtime.Given(value)", given)
      <> "\n      }"
    }
    None ->
      "option.Some(#("
      <> column_sql
      <> ", "
      <> insert_encoding(column, "new." <> field)
      <> "))"
  }
}

fn format_case_arm(indent: String, pattern: String, value: String) -> String {
  let compact = indent <> pattern <> " -> " <> value
  case string.length(compact) <= 80 {
    True -> compact
    False -> indent <> pattern <> " ->\n" <> indent <> "  " <> value
  }
}

fn insert_encoding(column: Column, value: String) -> String {
  case column.nullable {
    True -> "d1.nullable(" <> value <> ", " <> encoder(column.kind) <> ")"
    False -> encode(column.kind, value)
  }
}

fn encode(kind: Kind, value: String) -> String {
  encoder(kind) <> "(" <> value <> ")"
}

fn encoder(kind: Kind) -> String {
  case kind {
    schema.IntKind -> "d1.int"
    schema.FloatKind -> "d1.float"
    schema.TextKind -> "d1.string"
    schema.BoolKind -> "d1.bool"
    schema.TimestampKind -> "runtime.timestamp_value"
  }
}

fn column_decoder(column: Column) -> String {
  let decoder = case column.kind {
    schema.IntKind -> "d1.int_decoder()"
    schema.FloatKind -> "decode.float"
    schema.TextKind -> "decode.string"
    schema.BoolKind -> "d1.bool_decoder()"
    schema.TimestampKind -> "runtime.timestamp_decoder()"
  }
  case column.nullable {
    True -> "decode.optional(" <> decoder <> ")"
    False -> decoder
  }
}

fn column_type(column: Column) -> String {
  let base = base_type(column.kind)
  case column.nullable {
    True -> "option.Option(" <> base <> ")"
    False -> base
  }
}

fn insert_type(column: Column) -> String {
  let base = case column.nullable {
    True -> "option.Option(" <> base_type(column.kind) <> ")"
    False -> base_type(column.kind)
  }
  case column.default {
    Some(_) -> "runtime.Defaulted(" <> base <> ")"
    None -> base
  }
}

fn base_type(kind: Kind) -> String {
  case kind {
    schema.IntKind -> "Int"
    schema.FloatKind -> "Float"
    schema.TextKind -> "String"
    schema.BoolKind -> "Bool"
    schema.TimestampKind -> "timestamp.Timestamp"
  }
}

fn insertable(column: Column) -> Bool {
  column.primary_key == False || column.kind != schema.IntKind
}

fn primary_key(table: Table) -> Column {
  case list.find(table.columns, fn(column) { column.primary_key }) {
    Ok(column) -> column
    Error(Nil) -> panic as "validated snapshots have a primary key"
  }
}

fn table_uses_timestamp(table: Table) -> Bool {
  list.any(table.columns, fn(column) { column.kind == schema.TimestampKind })
}

fn table_uses_runtime(table: Table) -> Bool {
  list.any(table.columns, fn(column) {
    column.kind == schema.TimestampKind || column.default != None
  })
}

const reserved_words = "as assert auto case const delegate derive echo else fn if implement import let macro opaque panic pub test todo type use"

fn field_name(name: String) -> String {
  case string.split(reserved_words, " ") |> list.contains(name) {
    True -> name <> "_"
    False -> name
  }
}

fn quote_identifier(name: String) -> String {
  "\"" <> name <> "\""
}

fn gleam_string(value: String) -> String {
  "\"" <> string.replace(value, "\"", "\\\"") <> "\""
}

fn snake_case(name: String) -> String {
  name
  |> string.to_graphemes
  |> list.index_map(fn(char, index) {
    case index > 0 && string.contains("ABCDEFGHIJKLMNOPQRSTUVWXYZ", char) {
      True -> "_" <> string.lowercase(char)
      False -> string.lowercase(char)
    }
  })
  |> string.join("")
}
