//// Generates the typed D1 interface from a frozen schema snapshot.

import gleam/list
import gleam/option.{None, Some}
import gleam/string
import starflame_db/schema.{type Column, type Kind, type Table}
import starflame_db_kit/snapshot.{type Snapshot}

/// The module's source, laid out by `gleam format` so that it stays stable
/// under the app's own formatting check.
pub fn module(snapshot: Snapshot) -> Result(String, String) {
  format(source(snapshot))
}

@external(javascript, "../starflame_db_kit_ffi.mjs", "format")
fn format(source: String) -> Result(String, String)

fn source(snapshot: Snapshot) -> String {
  let tables = snapshot.canonical(snapshot.schema).tables
  let imports =
    case tables {
      [] -> []
      _ -> [
        "import gleam/dynamic",
        "import gleam/dynamic/decode",
        "import gleam/javascript/promise",
        "import gleam/list",
        "import gleam/option",
        "import starflame/d1",
        "import starflame/fast_decode",
      ]
    }
    |> list.append(case list.any(tables, has_insertable) {
      True -> ["import gleam/string"]
      False -> []
    })
    |> list.append(case list.any(tables, table_uses_timestamp) {
      True -> ["import gleam/time/timestamp"]
      False -> []
    })
    |> list.append(case list.any(tables, table_uses_runtime) {
      True -> ["import starflame_db/runtime"]
      False -> []
    })
    |> list.append(case tables {
      [] -> []
      _ -> ["import gleam/int"]
    })
    |> list.sort(string.compare)
  let header =
    "//// Generated by starflame_db_kit from snapshot "
    <> snapshot.id
    <> " ("
    <> snapshot.hash(snapshot)
    <> "). Do not edit;\n//// run `gleam run -m db_kit -- codegen` to regenerate."
  string.join(
    [header, string.join(imports, "\n"), ..list.map(tables, table_module)],
    "\n\n",
  )
  <> "\n"
}

fn table_module(table: Table) -> String {
  string.join(
    [
      row_type(table),
      new_type(table),
      columns_constant(table),
      decoder(table),
      insert_function(table),
      get_function(table),
      delete_function(table),
    ],
    "\n\n",
  )
}

fn row_type(table: Table) -> String {
  let fields =
    list.map(table.columns, fn(column) {
      field_name(column.name) <> ": " <> column_type(column)
    })
  custom_type(table.row, fields)
}

fn new_type(table: Table) -> String {
  let fields =
    list.filter(table.columns, insertable)
    |> list.map(fn(column) {
      field_name(column.name) <> ": " <> insert_type(column)
    })
  custom_type("New" <> table.row, fields)
}

fn custom_type(name: String, fields: List(String)) -> String {
  let constructor = case fields {
    [] -> name
    _ -> name <> "(" <> string.join(fields, ", ") <> ")"
  }
  "pub type " <> name <> " {\n  " <> constructor <> "\n}"
}

fn columns_constant(table: Table) -> String {
  "pub const "
  <> snake_case(table.row)
  <> "_columns = "
  <> gleam_string(
    table.columns
    |> list.map(fn(column) { quote_identifier(column.name) })
    |> string.join(", "),
  )
}

/// The private helpers are named so no other row type's generated names can
/// match them: `<row>_<anything>_decoder` would collide with the decoder of a
/// row named `<Row><Anything>`.
fn decoder(table: Table) -> String {
  let name = snake_case(table.row)
  let fields =
    list.map(table.columns, fn(column) {
      "fast_decode.Field("
      <> gleam_string(column.name)
      <> ", fast_decode."
      <> fast_kind(column.kind)
      <> ", "
      <> case column.nullable {
        True -> "True"
        False -> "False"
      }
      <> ")"
    })
  let reads =
    list.map(table.columns, fn(column) {
      field_name(column.name) <> ": " <> fast_read(column)
    })
  let checked =
    list.map(table.columns, fn(column) {
      "  use "
      <> field_name(column.name)
      <> " <- decode.field("
      <> gleam_string(column.name)
      <> ", "
      <> column_decoder(column)
      <> ")\n"
    })
  "/// Rows that match go through a fast path; others get the full decoder's\n"
  <> "/// errors.\n"
  <> "pub fn "
  <> name
  <> "_decoder() -> decode.Decoder("
  <> table.row
  <> ") {\n"
  <> "  fast_decode.decoder("
  <> name
  <> "_fields, "
  <> name
  <> "_from_row, "
  <> name
  <> "_fallback())\n}\n\n"
  <> "const "
  <> name
  <> "_fields = ["
  <> string.join(fields, ", ")
  <> "]\n\n"
  <> "fn "
  <> name
  <> "_from_row(row: dynamic.Dynamic) -> "
  <> table.row
  <> " {\n  "
  <> table.row
  <> "("
  <> string.join(reads, ", ")
  <> ")\n}\n\n"
  <> "fn "
  <> name
  <> "_fallback() -> decode.Decoder("
  <> table.row
  <> ") {\n"
  <> string.concat(checked)
  <> "  decode.success("
  <> table.row
  <> "("
  <> string.join(
    list.map(table.columns, fn(column) { field_name(column.name) <> ":" }),
    ", ",
  )
  <> "))\n}"
}

/// The fast path's check for a column, matching `column_decoder`.
fn fast_kind(kind: Kind) -> String {
  case kind {
    schema.IntKind | schema.TimestampKind -> "SafeIntKind"
    schema.FloatKind -> "FloatKind"
    schema.TextKind -> "StringKind"
    schema.BoolKind -> "ZeroOrOneKind"
  }
}

/// Reads a checked column, matching `column_decoder`.
fn fast_read(column: Column) -> String {
  let name = gleam_string(column.name)
  case column.nullable, column.kind {
    False, schema.BoolKind -> "fast_decode.zero_or_one(row, " <> name <> ")"
    False, schema.TimestampKind ->
      "timestamp.from_unix_seconds(fast_decode.get(row, " <> name <> "))"
    False, _ -> "fast_decode.get(row, " <> name <> ")"
    True, schema.BoolKind ->
      "fast_decode.nullable(row, " <> name <> ", fast_decode.zero_or_one)"
    True, schema.TimestampKind ->
      "fast_decode.nullable(row, "
      <> name
      <> ", fn(row, name) { timestamp.from_unix_seconds(fast_decode.get(row, name)) })"
    True, _ -> "fast_decode.nullable(row, " <> name <> ", fast_decode.get)"
  }
}

fn insert_function(table: Table) -> String {
  let row = table.row
  let name = snake_case(row)
  let default_values =
    gleam_string(
      "INSERT INTO "
      <> quote_identifier(table.name)
      <> " DEFAULT VALUES RETURNING ",
    )
    <> " <> "
    <> name
    <> "_columns"
  let body = case list.filter(table.columns, insertable) {
    // Nothing to insert but the rowid, so there is nothing to read from `new`.
    [] ->
      "  d1.all(db, " <> default_values <> ", [], " <> name <> "_decoder())\n"
    columns ->
      "  let values =\n    ["
      <> string.join(list.map(columns, insert_value), ", ")
      <> "]\n"
      <> "    |> list.filter_map(fn(value) {\n"
      <> "      case value {\n"
      <> "        option.Some(value) -> Ok(value)\n"
      <> "        option.None -> Error(Nil)\n"
      <> "      }\n"
      <> "    })\n"
      <> "  let sql = case values {\n"
      <> "    [] -> "
      <> default_values
      <> "\n    _ -> "
      <> gleam_string("INSERT INTO " <> quote_identifier(table.name) <> " (")
      <> " <> string.join(list.map(values, fn(value) { value.0 }), \", \")"
      <> " <> \") VALUES (\""
      <> " <> string.join(list.map(values, fn(_) { \"?\" }), \", \")"
      <> " <> \") RETURNING \" <> "
      <> name
      <> "_columns\n  }\n"
      <> "  d1.all(db, sql, list.map(values, fn(value) { value.1 }), "
      <> name
      <> "_decoder())\n"
  }
  let new = case has_insertable(table) {
    True -> "new"
    False -> "_new"
  }
  "pub fn insert_"
  <> name
  <> "(db: d1.Database, "
  <> new
  <> ": New"
  <> row
  <> ") -> promise.Promise(Result("
  <> row
  <> ", d1.Error)) {\n"
  <> body
  <> "  |> promise.map(fn(result) {\n"
  <> "    case result {\n"
  <> "      Ok([row]) -> Ok(row)\n"
  <> "      Ok(rows) -> Error(d1.DecodeError([decode.DecodeError(\"one row\", int.to_string(list.length(rows)) <> \" rows\", [])]))\n"
  <> "      Error(error) -> Error(error)\n"
  <> "    }\n"
  <> "  })\n}"
}

fn get_function(table: Table) -> String {
  let name = snake_case(table.row)
  let key = primary_key(table)
  let key_name = field_name(key.name)
  let columns =
    table.columns
    |> list.map(fn(column) { quote_identifier(column.name) })
    |> string.join(", ")
  "pub fn get_"
  <> name
  <> "(db: d1.Database, "
  <> key_name
  <> ": "
  <> base_type(key.kind)
  <> ") -> promise.Promise(Result(option.Option("
  <> table.row
  <> "), d1.Error)) {\n"
  <> "  d1.all(db, "
  <> gleam_string(
    "SELECT "
    <> columns
    <> " FROM "
    <> quote_identifier(table.name)
    <> " WHERE "
    <> quote_identifier(key.name)
    <> " = ?",
  )
  <> ", ["
  <> encode(key.kind, key_name)
  <> "], "
  <> name
  <> "_decoder())\n"
  <> "  |> promise.map(fn(result) {\n"
  <> "    case result {\n"
  <> "      Ok([row, ..]) -> Ok(option.Some(row))\n"
  <> "      Ok([]) -> Ok(option.None)\n"
  <> "      Error(error) -> Error(error)\n"
  <> "    }\n"
  <> "  })\n}"
}

fn delete_function(table: Table) -> String {
  let name = snake_case(table.row)
  let key = primary_key(table)
  let key_name = field_name(key.name)
  let query =
    "DELETE FROM "
    <> quote_identifier(table.name)
    <> " WHERE "
    <> quote_identifier(key.name)
    <> " = ?"
  "pub fn delete_"
  <> name
  <> "(db: d1.Database, "
  <> key_name
  <> ": "
  <> base_type(key.kind)
  <> ") -> promise.Promise(Result(Bool, d1.Error)) {\n"
  <> "  d1.run(db, "
  <> gleam_string(query)
  <> ", ["
  <> encode(key.kind, key_name)
  <> "])\n"
  <> "  |> promise.map(fn(result) {\n"
  <> "    case result {\n"
  <> "      Ok(changes) -> Ok(changes > 0)\n"
  <> "      Error(error) -> Error(error)\n"
  <> "    }\n"
  <> "  })\n}"
}

fn insert_value(column: Column) -> String {
  let field = field_name(column.name)
  let column_sql = gleam_string(quote_identifier(column.name))
  case column.default {
    Some(_) ->
      "case new."
      <> field
      <> " {\n runtime.UseDefault -> option.None\n runtime.Given(value) -> option.Some(#("
      <> column_sql
      <> ", "
      <> insert_encoding(column, "value")
      <> "))\n}"
    None ->
      "option.Some(#("
      <> column_sql
      <> ", "
      <> insert_encoding(column, "new." <> field)
      <> "))"
  }
}

fn insert_encoding(column: Column, value: String) -> String {
  case column.nullable {
    True -> "d1.nullable(" <> value <> ", " <> encoder(column.kind) <> ")"
    False -> encode(column.kind, value)
  }
}

fn encode(kind: Kind, value: String) -> String {
  encoder(kind) <> "(" <> value <> ")"
}

fn encoder(kind: Kind) -> String {
  case kind {
    schema.IntKind -> "d1.int"
    schema.FloatKind -> "d1.float"
    schema.TextKind -> "d1.string"
    schema.BoolKind -> "d1.bool"
    schema.TimestampKind -> "runtime.timestamp_value"
  }
}

fn column_decoder(column: Column) -> String {
  let decoder = case column.kind {
    schema.IntKind -> "d1.int_decoder()"
    schema.FloatKind -> "decode.float"
    schema.TextKind -> "decode.string"
    schema.BoolKind -> "d1.bool_decoder()"
    schema.TimestampKind -> "runtime.timestamp_decoder()"
  }
  case column.nullable {
    True -> "decode.optional(" <> decoder <> ")"
    False -> decoder
  }
}

fn column_type(column: Column) -> String {
  let base = base_type(column.kind)
  case column.nullable {
    True -> "option.Option(" <> base <> ")"
    False -> base
  }
}

fn insert_type(column: Column) -> String {
  let base = case column.nullable {
    True -> "option.Option(" <> base_type(column.kind) <> ")"
    False -> base_type(column.kind)
  }
  case column.default {
    Some(_) -> "runtime.Defaulted(" <> base <> ")"
    None -> base
  }
}

fn base_type(kind: Kind) -> String {
  case kind {
    schema.IntKind -> "Int"
    schema.FloatKind -> "Float"
    schema.TextKind -> "String"
    schema.BoolKind -> "Bool"
    schema.TimestampKind -> "timestamp.Timestamp"
  }
}

fn insertable(column: Column) -> Bool {
  column.primary_key == False || column.kind != schema.IntKind
}

fn primary_key(table: Table) -> Column {
  case list.find(table.columns, fn(column) { column.primary_key }) {
    Ok(column) -> column
    Error(Nil) -> panic as "validated snapshots have a primary key"
  }
}

fn table_uses_timestamp(table: Table) -> Bool {
  list.any(table.columns, fn(column) { column.kind == schema.TimestampKind })
}

fn table_uses_runtime(table: Table) -> Bool {
  list.any(table.columns, fn(column) {
    column.kind == schema.TimestampKind
    || insertable(column)
    && column.default != None
  })
}

fn has_insertable(table: Table) -> Bool {
  list.any(table.columns, insertable)
}

const reserved_words = "as assert auto case const delegate derive echo else fn if implement import let macro opaque panic pub test todo type use"

fn field_name(name: String) -> String {
  case string.split(reserved_words, " ") |> list.contains(name) {
    True -> name <> "_"
    False -> name
  }
}

fn quote_identifier(name: String) -> String {
  "\"" <> name <> "\""
}

fn gleam_string(value: String) -> String {
  "\"" <> string.replace(value, "\"", "\\\"") <> "\""
}

fn snake_case(name: String) -> String {
  name
  |> string.to_graphemes
  |> list.index_map(fn(char, index) {
    case index > 0 && string.contains("ABCDEFGHIJKLMNOPQRSTUVWXYZ", char) {
      True -> "_" <> string.lowercase(char)
      False -> string.lowercase(char)
    }
  })
  |> string.join("")
}
