//// Generated by starflame_db_kit from snapshot 0001_init (6feae39309e71347). Do not edit;
//// run `gleam run -m db_kit -- codegen` to regenerate.

import gleam/dynamic
import gleam/dynamic/decode
import gleam/int
import gleam/javascript/promise
import gleam/list
import gleam/option
import gleam/string
import gleam/time/timestamp
import starflame/d1
import starflame/fast_decode
import starflame_db/runtime

pub type Note {
  Note(id: Int, user_id: Int, body: String, created_at: timestamp.Timestamp)
}

pub type NewNote {
  NewNote(
    user_id: Int,
    body: String,
    created_at: runtime.Defaulted(timestamp.Timestamp),
  )
}

pub const note_columns = "\"id\", \"user_id\", \"body\", \"created_at\""

/// Rows that match go through a fast path; others get the full decoder's
/// errors.
pub fn note_decoder() -> decode.Decoder(Note) {
  fast_decode.decoder(note_fields, note_from_row, note_fallback())
}

const note_fields = [
  fast_decode.Field("id", fast_decode.SafeIntKind, False),
  fast_decode.Field("user_id", fast_decode.SafeIntKind, False),
  fast_decode.Field("body", fast_decode.StringKind, False),
  fast_decode.Field("created_at", fast_decode.SafeIntKind, False),
]

fn note_from_row(row: dynamic.Dynamic) -> Note {
  Note(
    id: fast_decode.get(row, "id"),
    user_id: fast_decode.get(row, "user_id"),
    body: fast_decode.get(row, "body"),
    created_at: timestamp.from_unix_seconds(fast_decode.get(row, "created_at")),
  )
}

fn note_fallback() -> decode.Decoder(Note) {
  use id <- decode.field("id", d1.int_decoder())
  use user_id <- decode.field("user_id", d1.int_decoder())
  use body <- decode.field("body", decode.string)
  use created_at <- decode.field("created_at", runtime.timestamp_decoder())
  decode.success(Note(id:, user_id:, body:, created_at:))
}

pub fn insert_note(
  db: d1.Database,
  new: NewNote,
) -> promise.Promise(Result(Note, d1.Error)) {
  let values =
    [
      option.Some(#("\"user_id\"", d1.int(new.user_id))),
      option.Some(#("\"body\"", d1.string(new.body))),
      case new.created_at {
        runtime.UseDefault -> option.None
        runtime.Given(value) ->
          option.Some(#("\"created_at\"", runtime.timestamp_value(value)))
      },
    ]
    |> list.filter_map(fn(value) {
      case value {
        option.Some(value) -> Ok(value)
        option.None -> Error(Nil)
      }
    })
  let sql = case values {
    [] -> "INSERT INTO \"notes\" DEFAULT VALUES RETURNING " <> note_columns
    _ ->
      "INSERT INTO \"notes\" ("
      <> string.join(list.map(values, fn(value) { value.0 }), ", ")
      <> ") VALUES ("
      <> string.join(list.map(values, fn(_) { "?" }), ", ")
      <> ") RETURNING "
      <> note_columns
  }
  d1.all(db, sql, list.map(values, fn(value) { value.1 }), note_decoder())
  |> promise.map(fn(result) {
    case result {
      Ok([row]) -> Ok(row)
      Ok(rows) ->
        Error(
          d1.DecodeError([
            decode.DecodeError(
              "one row",
              int.to_string(list.length(rows)) <> " rows",
              [],
            ),
          ]),
        )
      Error(error) -> Error(error)
    }
  })
}

pub fn get_note(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(option.Option(Note), d1.Error)) {
  d1.all(
    db,
    "SELECT \"id\", \"user_id\", \"body\", \"created_at\" FROM \"notes\" WHERE \"id\" = ?",
    [d1.int(id)],
    note_decoder(),
  )
  |> promise.map(fn(result) {
    case result {
      Ok([row, ..]) -> Ok(option.Some(row))
      Ok([]) -> Ok(option.None)
      Error(error) -> Error(error)
    }
  })
}

pub fn delete_note(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(Bool, d1.Error)) {
  d1.run(db, "DELETE FROM \"notes\" WHERE \"id\" = ?", [d1.int(id)])
  |> promise.map(fn(result) {
    case result {
      Ok(changes) -> Ok(changes > 0)
      Error(error) -> Error(error)
    }
  })
}

pub type User {
  User(
    id: Int,
    email: String,
    google_subject: option.Option(String),
    created_at: timestamp.Timestamp,
  )
}

pub type NewUser {
  NewUser(
    email: String,
    google_subject: option.Option(String),
    created_at: runtime.Defaulted(timestamp.Timestamp),
  )
}

pub const user_columns = "\"id\", \"email\", \"google_subject\", \"created_at\""

/// Rows that match go through a fast path; others get the full decoder's
/// errors.
pub fn user_decoder() -> decode.Decoder(User) {
  fast_decode.decoder(user_fields, user_from_row, user_fallback())
}

const user_fields = [
  fast_decode.Field("id", fast_decode.SafeIntKind, False),
  fast_decode.Field("email", fast_decode.StringKind, False),
  fast_decode.Field("google_subject", fast_decode.StringKind, True),
  fast_decode.Field("created_at", fast_decode.SafeIntKind, False),
]

fn user_from_row(row: dynamic.Dynamic) -> User {
  User(
    id: fast_decode.get(row, "id"),
    email: fast_decode.get(row, "email"),
    google_subject: fast_decode.nullable(row, "google_subject", fast_decode.get),
    created_at: timestamp.from_unix_seconds(fast_decode.get(row, "created_at")),
  )
}

fn user_fallback() -> decode.Decoder(User) {
  use id <- decode.field("id", d1.int_decoder())
  use email <- decode.field("email", decode.string)
  use google_subject <- decode.field(
    "google_subject",
    decode.optional(decode.string),
  )
  use created_at <- decode.field("created_at", runtime.timestamp_decoder())
  decode.success(User(id:, email:, google_subject:, created_at:))
}

pub fn insert_user(
  db: d1.Database,
  new: NewUser,
) -> promise.Promise(Result(User, d1.Error)) {
  let values =
    [
      option.Some(#("\"email\"", d1.string(new.email))),
      option.Some(#(
        "\"google_subject\"",
        d1.nullable(new.google_subject, d1.string),
      )),
      case new.created_at {
        runtime.UseDefault -> option.None
        runtime.Given(value) ->
          option.Some(#("\"created_at\"", runtime.timestamp_value(value)))
      },
    ]
    |> list.filter_map(fn(value) {
      case value {
        option.Some(value) -> Ok(value)
        option.None -> Error(Nil)
      }
    })
  let sql = case values {
    [] -> "INSERT INTO \"users\" DEFAULT VALUES RETURNING " <> user_columns
    _ ->
      "INSERT INTO \"users\" ("
      <> string.join(list.map(values, fn(value) { value.0 }), ", ")
      <> ") VALUES ("
      <> string.join(list.map(values, fn(_) { "?" }), ", ")
      <> ") RETURNING "
      <> user_columns
  }
  d1.all(db, sql, list.map(values, fn(value) { value.1 }), user_decoder())
  |> promise.map(fn(result) {
    case result {
      Ok([row]) -> Ok(row)
      Ok(rows) ->
        Error(
          d1.DecodeError([
            decode.DecodeError(
              "one row",
              int.to_string(list.length(rows)) <> " rows",
              [],
            ),
          ]),
        )
      Error(error) -> Error(error)
    }
  })
}

pub fn get_user(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(option.Option(User), d1.Error)) {
  d1.all(
    db,
    "SELECT \"id\", \"email\", \"google_subject\", \"created_at\" FROM \"users\" WHERE \"id\" = ?",
    [d1.int(id)],
    user_decoder(),
  )
  |> promise.map(fn(result) {
    case result {
      Ok([row, ..]) -> Ok(option.Some(row))
      Ok([]) -> Ok(option.None)
      Error(error) -> Error(error)
    }
  })
}

pub fn delete_user(
  db: d1.Database,
  id: Int,
) -> promise.Promise(Result(Bool, d1.Error)) {
  d1.run(db, "DELETE FROM \"users\" WHERE \"id\" = ?", [d1.int(id)])
  |> promise.map(fn(result) {
    case result {
      Ok(changes) -> Ok(changes > 0)
      Error(error) -> Error(error)
    }
  })
}
