-- Generated by starflame_db_kit. Review before applying with `wrangler d1 migrations apply`.
-- parent: none
-- snapshot: 4fb2002b68c40bf5

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "admin" INTEGER NOT NULL DEFAULT 0 CHECK ("admin" IN (0, 1)),
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch()),
  "bio" TEXT,
  CONSTRAINT "users_email_at" CHECK (instr(email, '@') > 1)
) STRICT;
CREATE TABLE "posts" (
  "id" INTEGER PRIMARY KEY,
  "user_id" INTEGER NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "title" TEXT NOT NULL,
  "body" TEXT DEFAULT '',
  "type" TEXT NOT NULL DEFAULT 'article',
  "rating" REAL
) STRICT;
CREATE TABLE "comments" (
  "id" INTEGER PRIMARY KEY,
  "post_id" INTEGER NOT NULL REFERENCES "posts" ("id") ON DELETE CASCADE,
  "editor_id" INTEGER REFERENCES "users" ("id") ON DELETE SET NULL,
  "body" TEXT NOT NULL
) STRICT;
CREATE INDEX "users_name_idx" ON "users" ("name");
CREATE INDEX "posts_user_idx" ON "posts" ("user_id");
