-- Generated by starflame_db_kit. Review before applying with `wrangler d1 migrations apply`.
-- parent: 4fb2002b68c40bf5
-- snapshot: ff7292f88e62a7d8

ALTER TABLE "posts" ADD COLUMN "slug" TEXT NOT NULL DEFAULT 'pending';
