-- Generated by starflame_db_kit. Review before applying with `wrangler d1 migrations apply`.
-- parent: ff7292f88e62a7d8
-- snapshot: fd00c3eb3746e563
-- rename users.name to display_name

ALTER TABLE "users" RENAME COLUMN "name" TO "display_name";
