-- Generated by starflame_db_kit. Review before applying with `wrangler d1 migrations apply`.
-- parent: 5fc94c37a541d229
-- snapshot: c6c567f28ebf5bea
-- rebuild users: checks changed
-- rebuild comments: references a rebuilt table, and D1 cannot disable foreign keys
-- rebuild posts: references a rebuilt table, and D1 cannot disable foreign keys

PRAGMA defer_foreign_keys = ON;
CREATE TABLE "__sf_bak_comments" AS SELECT "id", "post_id", "editor_id", "body" FROM "comments";
CREATE TABLE "__sf_bak_posts" AS SELECT "id", "user_id", "title", "slug", "body", "type", "rating" FROM "posts";
CREATE TABLE "__sf_bak_users" AS SELECT "id", "email", "display_name", "admin", "created_at", "bio" FROM "users";
DROP TABLE "comments";
DROP TABLE "posts";
DROP TABLE "users";
CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "display_name" TEXT NOT NULL,
  "admin" INTEGER NOT NULL DEFAULT 0 CHECK ("admin" IN (0, 1)),
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch()),
  "bio" TEXT,
  CONSTRAINT "users_email_at" CHECK (instr(email, '@') > 1),
  CONSTRAINT "users_display_name_nonempty" CHECK (length(display_name) > 0)
) STRICT;
CREATE TABLE "posts" (
  "id" INTEGER PRIMARY KEY,
  "user_id" INTEGER NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL DEFAULT 'pending',
  "body" TEXT DEFAULT '',
  "type" TEXT NOT NULL DEFAULT 'article',
  "rating" REAL
) STRICT;
CREATE TABLE "comments" (
  "id" INTEGER PRIMARY KEY,
  "post_id" INTEGER NOT NULL REFERENCES "posts" ("id") ON DELETE CASCADE,
  "editor_id" INTEGER REFERENCES "users" ("id") ON DELETE SET NULL,
  "body" TEXT NOT NULL
) STRICT;
INSERT INTO "users" ("id", "email", "display_name", "admin", "created_at", "bio") SELECT "id", "email", "display_name", "admin", "created_at", "bio" FROM "__sf_bak_users";
INSERT INTO "posts" ("id", "user_id", "title", "slug", "body", "type", "rating") SELECT "id", "user_id", "title", "slug", "body", "type", "rating" FROM "__sf_bak_posts";
INSERT INTO "comments" ("id", "post_id", "editor_id", "body") SELECT "id", "post_id", "editor_id", "body" FROM "__sf_bak_comments";
DROP TABLE "__sf_bak_comments";
DROP TABLE "__sf_bak_posts";
DROP TABLE "__sf_bak_users";
CREATE INDEX "posts_user_idx" ON "posts" ("user_id");
CREATE INDEX "users_name_idx" ON "users" ("display_name");
