name = "starflame_rpc_kit"
version = "0.1.0"
target = "javascript"
description = "Generates Starflame's RPC codecs, dispatchers and client stubs"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
argv = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
